//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Contact
    {
        public decimal id { get; set; }
        public string ip { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        [Required(ErrorMessage = "Tên không được để trống!")]
        public string name { get; set; }
        [Required(ErrorMessage = "Mail không được để trống!")]
        [EmailAddress(ErrorMessage ="Email không hợp lệ!")]
        public string email { get; set; }
        [Required(ErrorMessage = "Tiêu đề không được để trống!")]
        public string tieude { get; set; }
        [Required(ErrorMessage = "Nội dung không được để trống!")]
        public string noidung { get; set; }
        public Nullable<bool> trangthai { get; set; }
    }
}
