//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public decimal id { get; set; }
        public string title { get; set; }
        public string img { get; set; }
        public string tag { get; set; }
        public Nullable<System.DateTime> day { get; set; }
        public Nullable<int> nview { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<int> nrate { get; set; }
        public string contents { get; set; }
        public Nullable<System.DateTime> dayupdate { get; set; }
        public string usercreate { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
