//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message2s
    {
        public string Message { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public decimal id { get; set; }
    }
}
