//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Comments = new HashSet<Comment>();
            this.Images = new HashSet<Image>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ID { get; set; }
        public string MaSanPham { get; set; }
        [Required(ErrorMessage = "Tên không được để trống!")]
        public string TenSanPham { get; set; }
        public Nullable<int> LoaiSP { get; set; }
        [Required(ErrorMessage = "Giá không được để trống!")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Giá phải là số nguyên!")]
        public Nullable<double> Gia { get; set; }
        [Required(ErrorMessage = "Xuất xứ không được để trống!")]
        public string XuatXu { get; set; }
        [Required(ErrorMessage = "Nồng độ không được để trống!")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Nồng độ phải là số nguyên!")]
        public Nullable<double> NongDo { get; set; }
        [Required(ErrorMessage = "Dung tích không được để trống!")]
        [RegularExpression("^(?!0\\d)\\d*(\\.\\d+)?$", ErrorMessage = "Dung tích là số thực!")]
        public Nullable<double> DungTich { get; set; }
        public Nullable<int> SoLuotXem { get; set; }
        public Nullable<int> TinhTrang { get; set; }
        public string Tag { get; set; }
        [Required(ErrorMessage = "Mô tả không được để trống!")]
        public string MoTa { get; set; }
        [Required(ErrorMessage = "Số lượng tồn không được để trống!")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Số lượng tồn phải là số nguyên!")]
        public Nullable<int> SoLuongTon { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> NhaSanXuat { get; set; }
        public Nullable<int> ThuongHieu { get; set; }
        public string ChiTietBoSung { get; set; }
        [Required(ErrorMessage = "Giá khuyến mãi không được để trống!")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Giá khuyến mãi phải là số nguyên!")]
        public Nullable<double> GiaKhuyenMai { get; set; }
        [Required(ErrorMessage = "Năm sản xuất không được để trống!")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Năm sản xuất phải là số nguyên lớn hơn 0!")]
        public Nullable<int> NamSanXuat { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public string TuKhoa { get; set; }
        public Nullable<int> SoLuotMua { get; set; }
        public string url_img { get; set; }
        public string Seri { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> TypeView { get; set; }
        public Nullable<double> Nrate { get; set; }
        public Nullable<int> NReViews { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual TrangThai TrangThai { get; set; }
    }
}
