//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReView
    {
        public int ID { get; set; }
        public Nullable<int> Products_ID { get; set; }
        public string ReViews { get; set; }
        public Nullable<int> Rate { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string TacGia { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    }
}
