//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UaThich
    {
        public decimal id { get; set; }
        public Nullable<int> iduser { get; set; }
        public Nullable<int> idsanpham { get; set; }
        public string ip { get; set; }
        public string idwl { get; set; }
    }
}
