//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Website
    {
        [Required(ErrorMessage = "Vui lòng nhập số điện thoại 1")]
        [Display(Name = "Số điện thoại 1")]
        public string sdt1 { get; set; }
        [Display(Name = "Số điện thoại 2")]
        public string sdt2 { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        public string email { get; set; }
        [Display(Name = "Skype")]
        [MaxLength(40, ErrorMessage = "Skype có chiều dài tối đa là 40 kí tự")]
        [StringLength(100, ErrorMessage = "{0} có chiều dài ít nhất {2} kí tự.", MinimumLength = 6)]
        public string skype { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ")]
        [Display(Name = "Địa chỉ")]
        [MaxLength(40, ErrorMessage = "Địa chỉ có chiều dài tối đa là 40 kí tự")]
        [StringLength(100, ErrorMessage = "Địa chỉ có chiều dài ít nhất 6 kí tự.", MinimumLength = 6)]
        public string diachi { get; set; }
        [Display(Name = "Twitter")]
        [MaxLength(60, ErrorMessage = "Twitter có chiều dài tối đa là 60 kí tự")]
        [StringLength(100, ErrorMessage = "Twitter có chiều dài ít nhất 4 kí tự.", MinimumLength = 4)]
        public string twitter { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ facebook")]
        [Display(Name = "Facebook")]
        [MaxLength(60, ErrorMessage = "Facebook có chiều dài tối đa là 60 kí tự")]
        [StringLength(100, ErrorMessage = "Facebook có chiều dài ít nhất 4 kí tự.", MinimumLength = 4)]
        public string facebook { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập tên shop")]
        [Display(Name = "Tên shop")]
        [MaxLength(60, ErrorMessage = "Tên shop có chiều dài tối đa là 60 kí tự")]
        [StringLength(100, ErrorMessage = "Tên shop có chiều dài ít nhất 3 kí tự.", MinimumLength = 3)]
        public string tenshop { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ google map")]
        [Display(Name = "Google map")]
        [MaxLength(100, ErrorMessage = "Google map có chiều dài tối đa là 100 kí tự")]
        [StringLength(100, ErrorMessage = "Google map có chiều dài ít nhất 3 kí tự.", MinimumLength = 3)]
        public string googlemap { get; set; }
        [Required(ErrorMessage = "Vui lòng nhập địa chỉ host trang web")]
        [Display(Name = "Url")]
        [MaxLength(100, ErrorMessage = "Url có chiều dài tối đa là 100 kí tự")]
        [StringLength(100, ErrorMessage = "Url có chiều dài ít nhất 3 kí tự.", MinimumLength = 3)]
        public string linkWebsites { get; set; }
        public string favaicon { get; set; }
        public Nullable<System.DateTime> thoigiantao { get; set; }
        public Nullable<System.DateTime> thoigiancapnhat { get; set; }
        public string nguoichinhsua { get; set; }
        public string ghichi { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public decimal id { get; set; }
    }
}
